### ISSUE TITLE
US 02.02.01: Player Comment on QR Codes

### ISSUE THREAD

**Issue by toBFrank** [CMPUT301W23T05/supreme-waddle#11]
# As a player, I want to be able to comment on QR codes.

## Acceptance Criteria
- Have a (code) button for every code (human-readable name used)
- if (code) button clicked:
  - show details of code (score, location(s), drawing, etc.)
  - Have comment input box
  - Record + Display comment & player username
  - Have (ok) button to post comment

- Data:
  - Database of game-wide codes

**Comment by aarongeo1** [comment]
done
