### ISSUE TITLE
US 01.05.01: Player See Sum of QR Code Scores

### ISSUE THREAD

**Issue by toBFrank** [CMPUT301W23T05/supreme-waddle#7]
# As a player, I want to see the sum of scores of QR codes that I have scanned.

## Acceptance Criteria
- In home page, have (score sum) button as a number
- If (score sum) button clicked, bring to library
- In library, display score sum w/ highest + lowest scores
- Data:
  - Database of player-personal codes

**Comment by aarongeo1** [comment]
done
